import Link from 'next/link';
import Demo from '@/components/Demo';
import CopyCommand from '@/components/CopyCommand';
import DrillLibrary from '@/components/DrillLibrary';
const adapter = ['from breakroom import (', '    AgentContext, AgentResult,', '    SupportTools, TaskEnvelope,', ')', '', 'def run(task: TaskEnvelope,', '        tools: SupportTools,', '        context: AgentContext) -> AgentResult:', '    # Inject fake tools into your agent.', '    # Return claims from observed output.', '    return your_agent(task, tools, context)'].join('\n');
export default function Home() {
  return <>
    <section className="hero wrap"><div className="eyebrow"><span className="square" /> Crash tests for AI agents</div><div className="hero-grid"><h1>Break your agent.<br /><span>Not your business.</span></h1><div className="hero-aside"><p>Run your support agent through failed APIs, duplicate requests, and interrupted workflows—in a fake business environment, before it touches a real customer.</p><div className="hero-actions"><Link className="button accent" href="/signup">Start testing your agent <span>↗</span></Link><Link className="text-link" href="/demo">Try a Fire Drill <span>→</span></Link></div><span className="quiet-proof">24 Fire Drills. Private projects. Your own agent.</span></div></div></section>
    <section className="demo-section wrap"><div className="section-heading"><div><span className="eyebrow">FIRE DRILL 02 / THE MISSING RESPONSE</span><h2>The refund succeeded.<br />The response disappeared.</h2></div><p>Will your agent refund twice?<br /><span className="muted">Find out in a real test run.</span></p></div><Demo compact /></section>
    <section className="explain-section wrap"><div className="section-index">01 / LOOK PAST THE LAST MESSAGE</div><div className="explain-grid"><h2>The agent finished.<br /><span className="muted">The job did not.</span></h2><div><p>A tool timeout can hide a successful refund. Retry with a new key and a single request becomes two real effects in the simulated business.</p><p>Breakroom separates execution, business outcomes, safety checks, evidence quality, and fault coverage. A confident “done” is not enough.</p><Link href="/docs#verdicts" className="text-link">How a verdict is earned →</Link></div></div></section>
    <section className="library-section wrap"><div className="section-heading"><div><span className="eyebrow">CONTROLLED FAILURES. USEFUL LESSONS.</span><h2>Meet the Fire Drills.</h2></div><Link href="/fire-drills" className="text-link">Explore the library ↗</Link></div><DrillLibrary preview /></section>
    <section className="adapter-section wrap"><div className="adapter-copy"><span className="eyebrow">BRING YOUR AGENT. KEEP YOUR STACK.</span><h2>Your logic.<br />Our fake business.</h2><p>Connect a local Python adapter to TestPay and TestDesk. Exercise the workflow without touching a real customer.</p><Link className="text-link" href="/docs#adapter">Read the adapter tutorial →</Link></div><div className="code-window"><div><span>customer_agent.py</span><span>LOCAL ADAPTER</span></div><pre><code>{adapter}</code></pre><p>Trusted code, on your machine. A subprocess is not a security sandbox.</p></div></section>
    <section className="release-section wrap"><span className="eyebrow">CATCH IT BEFORE THE NEXT RELEASE</span><div className="explain-grid"><h2>Make the failure<br />a regression test.</h2><div><p>Export a versioned case with an executable test. Apply your own correction, then run the same fault and independent assertions again.</p><CopyCommand command="breakroom demo --output ./artifacts/demo" /><Link href="/docs#ci" className="text-link">Use Release Checks in CI →</Link></div></div></section>
    <section className="closing-section wrap"><div><span className="eyebrow">RUN LOCALLY. REVIEW TOGETHER.</span><h2>Your agent’s history.<br />Your team’s next move.</h2></div><div><p>Create a private workspace, connect your agent, and turn each run into evidence your team can act on. Build suites, investigate failed checks, compare corrections, and invite your teammates.</p><p className="muted">A passing suite demonstrates behavior under modeled conditions. It does not prove general agent safety.</p><Link href="/signup" className="button accent">Create your workspace →</Link></div></section>
  </>;
}
