'use client';
import { useEffect, useRef, useState } from 'react';
import Link from 'next/link';
import { teamApi } from '@/lib/team';

export default function AccountToken({ purpose }:{purpose:'verify'|'reset'}) {
  const parsed=useRef(false);
  const [token,setToken]=useState('');const [ready,setReady]=useState(false);const [done,setDone]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [password,setPassword]=useState('');const [confirmation,setConfirmation]=useState('');
  useEffect(()=>{if(parsed.current)return;parsed.current=true;const next=new URLSearchParams(window.location.hash.slice(1)).get('token')||'';if(/^[A-Za-z0-9_-]{43}$/.test(next))setToken(next);setReady(true);window.history.replaceState(null,'',window.location.pathname);},[]);
  async function submit(event:React.FormEvent){event.preventDefault();setError('');if(purpose==='reset'&&password!==confirmation){setError('The new passwords do not match.');return;}setBusy(true);try{await teamApi(purpose==='verify'?'auth/verify-email':'auth/reset-password',{method:'POST',body:purpose==='verify'?{token}:{token,password}});setToken('');setPassword('');setConfirmation('');setDone(true);}catch(e){setError(e instanceof Error?e.message:'This link could not be used.');}finally{setBusy(false);}}
  return <div className="account-token-page"><span className="eyebrow">ACCOUNT SECURITY</span><h1>{done?(purpose==='verify'?'Email verified.':'Password reset.'):(purpose==='verify'?'Verify your email.':'Choose a new password.')}</h1>{!ready&&<p role="status">Checking your link…</p>}{done?<><p>{purpose==='verify'?'Your email address is confirmed. You can return to your workspace or accept your team invitation.':'Your password has been changed and previous sessions have been signed out.'}</p><Link className="button accent" href={purpose==='verify'?'/projects':'/signin'}>{purpose==='verify'?'Go to workspace':'Sign in'}</Link></>:ready&&!token?<><p className="account-error" role="alert">This link is missing or invalid. Open the full link from your email, or request a new one.</p><Link href={purpose==='verify'?'/account':'/signin'} className="button outline">{purpose==='verify'?'Account settings':'Back to sign in'}</Link></>:token&&<form className="team-form" onSubmit={submit}>{purpose==='verify'?<p>Confirm that you want to verify the email address associated with this link.</p>:<><label>New password<input type="password" required minLength={12} maxLength={128} value={password} onChange={e=>setPassword(e.target.value)} autoComplete="new-password"/></label><label>Confirm new password<input type="password" required minLength={12} maxLength={128} value={confirmation} onChange={e=>setConfirmation(e.target.value)} autoComplete="new-password"/></label><p>Use 12–128 characters. Existing sessions will be signed out.</p></>}{error&&<p className="account-error" role="alert">{error}</p>}<button className="button accent" disabled={busy}>{busy?'Please wait…':purpose==='verify'?'Verify email':'Reset password'}</button></form>}</div>;
}
