'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { api, clearRecordings, readRecordings, Report, Run } from '@/lib/contracts';
import { Checks, EvidencePair, Status } from './Evidence';
import ExportLink from './ExportLink';

export function RunList() {
  const [runs, setRuns] = useState<Run[]>([]); const [notice, setNotice] = useState('');
  useEffect(() => { setRuns(readRecordings()); }, []);
  function clear() { try { clearRecordings(); setRuns([]); setNotice('Browser recordings cleared. API demo reports still expire automatically.'); } catch { setNotice('Browser storage could not be cleared.'); } }
  return <div className="wrap inner-page"><span className="eyebrow">THE EVIDENCE TRAIL</span><div className="section-heading"><h1>Runs<span>.</span></h1><Link className="button accent" href="/demo">Execute a new run ↗</Link></div><p className="lead">Saved recordings from this browser.<br />Viewing a recording does not execute an agent.</p><p className="scope-note">Demo API reports expire after 30 minutes or API restart. Up to 20 local browser recordings are retained until you clear them. No customer data is uploaded.</p>{notice && <p role="status">{notice}</p>}{!runs.length ? <div className="empty-surface"><span>∅</span><h2>No runs yet.</h2><p>Execute a scripted reference agent to begin your evidence trail.</p><Link href="/demo" className="text-link">Open the live demo →</Link></div> : <><div className="run-table">{runs.map(run => <Link className="saved-run" href={'/runs/' + run.id} key={run.id}><Status value={run.report.verdict} /><div><strong>{run.report.case.manifest.name}</strong><span>{run.agent} reference · engine {run.report.engine_version}</span></div><div><span>Fault coverage</span><Status value={run.report.checks.find(c => c.id === 'fault_coverage')?.status || 'unknown'} /></div><time dateTime={run.created_at}>{new Date(run.created_at).toLocaleString()}</time><span>↗</span></Link>)}</div><button className="button outline" onClick={clear}>Clear browser recordings</button></>}</div>;
}

export function RunDetail({ id }: { id: string }) {
  const [run, setRun] = useState<Run | null>(null); const [error, setError] = useState(''); const [recorded, setRecorded] = useState(false); const [available, setAvailable] = useState(false);
  useEffect(() => {
    const saved = readRecordings().find(r => r.id === id);
    if (saved) { setRun(saved); setRecorded(true); }
    api<Run>('runs/' + encodeURIComponent(id)).then(fresh => { setRun(fresh); setAvailable(true); }).catch(e => setError(e.message));
  }, [id]);
  if (!run) return <div className="wrap inner-page"><h1>{error ? 'Run unavailable' : 'Loading evidence…'}</h1>{error && <><p role="alert">{error}</p><Link className="button accent" href="/demo">Execute a new run →</Link></>}</div>;
  return <div className="wrap inner-page"><Link className="back-link" href="/runs">← All Runs</Link><span className="eyebrow">{recorded ? 'SAVED BROWSER RECORDING' : 'RECORDED API EVIDENCE'} / SCRIPTED REFERENCE</span><div className="section-heading"><h1>{run.report.case.manifest.name}</h1><Status value={run.report.verdict} /></div><p className="lead">{run.agent} reference · Execution {run.report.execution.status}</p><p className="scope-note">Executed {new Date(run.created_at).toLocaleString()}. This page displays recorded evidence; it is not a new execution. Simulated customers, money, services and faults.</p>{error && <div className="light-error" role="status">{error} {recorded && 'A local recording remains available below.'}</div>}<div className="detail-actions">{available ? <ExportLink id={run.id} className="button accent" /> : <span className="unavailable-label">Export unavailable after API evidence expiry. Run the drill again to export.</span>}<Link className="button outline" href={'/fire-drills/' + run.report.case.case_id}>Run this Fire Drill again →</Link></div><div className="demo-shell detail-evidence"><EvidencePair report={run.report} /></div><div className="investigator"><aside><span className="eyebrow">RELEASE CHECKS</span><Checks checks={run.report.checks} /></aside><section><h2>Ordered event log</h2><p>Includes authoritative effects and fault triggers the agent could not see.</p>{run.report.events.map((event, index) => <details className="light-event" key={String(event.id || index)}><summary><code>{String(event.id || index + 1)}</code><strong>{String(event.kind || event.type || 'event').replaceAll('_', ' ')}</strong><span>{String(event.tool || '')}</span></summary><pre>{JSON.stringify(event, null, 2)}</pre></details>)}</section><section><h2>State & contract</h2><div className="contract-meta"><span>Case v{run.report.case.case_version}</span><span>Engine {run.report.engine_version}</span><span>Oracle {run.report.oracle_version}</span><span>Seed {run.report.seed}</span></div>{(['initial_state', 'final_state'] as const).map(key => <details key={key} className="light-event"><summary>{key.replaceAll('_',' ')}</summary><pre>{JSON.stringify(run.report[key], null, 2)}</pre></details>)}<h3>Limitations</h3><ul>{run.report.limitations.map(l => <li key={l}>{l}</li>)}</ul></section></div></div>;
}
